#!/usr/bin/env zsh

# Logging functions

e_header() {
    printf "\n$(tput setaf 7)%s:$(tput sgr0) \n" "$@"
}

e_success() {
    printf "$(tput setaf 2)✓ Success:$(tput sgr0) %s\n" "$@"
}

e_error() {
    printf "$(tput setaf 1)⊘ Error:$(tput sgr0) %s. Aborting!\n" "$@"
}

e_warning() {
    printf "$(tput setaf 3)⚠ Warning:$(tput sgr0) %s!\n" "$@"
}

e_question() {
    printf "\n$(tput setaf 3)==> %s?$(tput sgr0) " "$@"
}

e_process() {
    printf "$(tput setaf 6)┃$(tput sgr0)$(tput setaf 7) %s...$(tput sgr0)\n" "$@"
}

# Utility functions

logging() {
    # write your test however you want; this just tests if SILENT is non-empty
    if [ -n "$SILENT" ]; then
        "$@" &> /dev/null
    else
        "$@"
    fi
}

seek_confirmation() {
    printf "\n"
    e_question "$@"
    read -r -n 1 REPLY

    if [[ -z "$REPLY" ]]; then
        REPLY="Y"
    fi

    printf "\n"
}

is_confirmed() {
    [[ "$REPLY" =~ ^[Yy]$ ]]
}

is_git_repo() {
    git rev-parse --is-inside-work-tree &> /dev/null
}

type_exists() {
    type "$1" > /dev/null
}

array_contains() {
    local seeking=$1
    shift
    for element; do
        if [[ $element == "$seeking" ]]; then
            return 0
        fi
    done
    return 1
}
